name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v7

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true

      - name: Run Tests
        run: |
          nvim --version
          ./tests/run.sh
